name: u24-runson-arm-int

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 
      - runs-on
      - runner=1cpu-linux-arm64
      - run-id=${{ github.run_id }}
    steps:
    - name: Test bug 1
      run: |
        sudo apt-get update
        sudo apt-get install libssl-dev -y
    - uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

